dataset:
  name: PDE_KS
  pair_id: [9]
model:
  name: spacetime
  seed: 0
  model: "ode-lstm" # ode-lstm or lstm
  solver: "fixed_rk4"
  hidden_state_size: 128
  seq_length: 50
  epochs: 3
  gradient_clip_val: 1.0
  accelerator: "auto"
  log_every_n_steps: 1
  "1"
  lr: 0.01
  seed: 0
