dataset:
  name: ODE_Lorenz
  pair_id:
  - 7
model:
  batch_size: 5
  epochs: 2
  gradient_clip_val: 1.0
  hidden_state_size: 8
  log_every_n_steps: 1
  lr: 0.009286391768229187
  model: ode-lstm
  name: spacetime
  seed: 0
  seq_length: 39
  solver: fixed_rk4
