dataset:
  name: PDE_KS
  pair_id:
  - 8
model:
  accelerator: auto
  epochs: 3
  gpu: auto
  gradient_clip_val: 1.0
  hidden_state_size: 256
  log_every_n_steps: 1
  lr: 0.00016274711850150102
  model: ode-lstm
  name: spacetime
  seed: 0
  seq_length: 10
  solver: fixed_rk4
