dataset:
  name: ODE_Lorenz
  pair_id:
  - 8
hyperparameters:
  hidden_state_size:
    lower_bound: 8
    type: randint
    upper_bound: 256
  lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  seq_length:
    lower_bound: 5
    type: randint
    upper_bound: 45
model:
  accelerator: auto
  epochs: 200
  gpu: auto
  gradient_clip_val: 1.0
  log_every_n_steps: 1
  model: ode-lstm
  n_trials: 1000
  name: spacetime
  seed: 0
  solver: fixed_rk4
  train_split: 0.8
