dataset:
  name: ODE_Lorenz
  pair_id:
  - 8
hyperparameters:
  hidden_state_size:
    lower_bound: 3
    type: randint
    upper_bound: 32
  lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  seq_length:
    lower_bound: 5
    type: randint
    upper_bound: 74
model:
  batch_size: 128
  epochs: 200
  gradient_clip_val: 1.0
  model: lstm
  n_trials: 999999999
  name: spacetime
  seed: 0
  solver: fixed_rk4
  train_split: 0.8
