dataset:
  name: ODE_Lorenz
  pair_id:
  - 4
hyperparameters:
  hidden_state_size:
    lower_bound: 3
    type: randint
    upper_bound: 32
  lr:
    lower_bound: 1.0e-05
    type: loguniform
    upper_bound: 0.01
  seq_length:
    lower_bound: 8
    type: randint
    upper_bound: 256
model:
  batch_size: 128
  epochs: 2
  gradient_clip_val: 1.0
  model: ode-lstm
  n_trials: 2
  name: spacetime
  seed: 0
  solver: fixed_rk4
  train_split: 0.8
