dataset:
  name: ODE_Lorenz
  pair_id: [8]
model:
  name: spacetime
  seed: 0
  n_trials: 2
  epochs: 3
  model: ode-lstm
  solver: fixed_rk4
  epochs: 2
  gradient_clip_val: 1.0
  accelerator: auto
  gpu: auto
  log_every_n_steps: 1
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
hyperparameters:
  hidden_state_size:
    type: choice
    choices: [8,16,32,64,128,256]
  seq_length:
    type: choice
    choices: [10,20,30,40,50,100,200]
  lr:
    type: loguniform
    lower_bound: 0.0001
    upper_bound: 0.01
