dataset:
  name: PDE_KS
  pair_id: [8]
model:
  name: ode-lstm
  train_split: 0.8
  n_trials: 2
  seed: 0
  epochs: 3
hyperparameters:
  hidden_state_size:
    type: choice
    choices: [8,16,32,64,128,256]
  seq_length:
    type: choice
    choices: [10,20,30,40,50,100,200]
  lr:
    type: loguniform
    lower_bound: 0.0001
    upper_bound: 0.01
